### ISSUE TITLE
Compiled whitch ARDUINO IDE 

### ISSUE THREAD

**Issue by micha6554** [qqqlab/DALI-Lighting-Interface#1]
Compiled whitch ARDUINO IDE  it's possible?

Thanks

**Comment by qqqlab** [comment]
Yes, download ZIP from github, then add it to the Arduino IDE with menu Sketch->Include Library->Add .ZIP Library. Then look under File->Examples->qqqDALI.

Examples for atmega328 are included, for other microcontrollers you'll have to write some code to call Dali::timer() every 107 microseconds.
